version: "3.9"

services:
  kong:
    build: .
    container_name: kong-gateway
    ports:
      - "8000:8000"   # API Gateway (HTTP)
      - "8443:8443"   # API Gateway (HTTPS)
      - "8001:8001"   # Admin API (HTTP)
      - "8444:8444"   # Admin API (HTTPS)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yaml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      INTERNAL_KEY: dfb6659c68c52305c5adbdc59c77b7f3d6235705327cb9bf4c37c96baf1fe1bd # Chiave segreta per comunicazioni interne
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    container_name: kong-dashboard
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
      KONGA_SEED_KONG_NODE_DATA: "true"
      KONGA_SEED_KONG_NODE_NAME: "Kong Local"
      KONGA_SEED_KONG_NODE_URL: "http://kong:8001"
    networks:
      - kong-net
    depends_on:
      - kong

networks:
  kong-net:
    driver: bridge
